services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-academy}
      POSTGRES_USER: ${POSTGRES_USER:-academy}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-academy}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: infra/docker/web.Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: ["/app/entrypoint.sh"]
volumes:
  db-data:
